default: &default
  adapter: postgresql
  database: berkana
  username: torero
  password: vPSHU2NgMF
  
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: berkana_theater_development

test:
  <<: *default
  database: berkana_theater_test

production:
  <<: *default
  database: berkana_theater_production